app:
  name: products-service

docker:
  image: guanwei/products-service:latest

aws:
  vpc: vpc-xxx
  region: xxx
  subnets:
    - subnet-xxx-A
    - subnet-xxx-B
  load_balancers:
    name: products-service-xxx
    dns: products-service-elb.xxx.amazonaws.com
  instances:
    type: t2.micro
    key_pair: products-service
    min: 1
    max: 2

splunk:
  host: splunk-test-xxx.microservice-in-action.com
  index: products-service

nagios:
  host: nagios-test-xxx.microservice-in-action.com